name: hello world workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  run-my-script:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/test-repo
          repository: "extendedkalman/test-repo"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Run Python Script
        run: |
          $scriptPath=.\test-repo\src\hello.py
          python $scriptPath

      - name: test uses action file
        uses: ./test-repo/.github/actions/test
        with:
          message: "testing local include"

  run-test-repo2:
    runs-on: windows-latest
    steps:
      - name: checkout repo2
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/test-repo2
          repository: "extendedkalman/test-repo2"

      - name: test uses action file
        uses: ./test-repo2/.github/actions/test
        with:
          message: "testing local include"

  testing-id:
    runs-on: windows-latest
    steps:
      - name: test powershell
        id: test-powershell
        shell: powershell
        run: |
          path="Hello World 123"

      - name: testing output
        shell: powershell
        run: |
          Write-Output "${{ steps.test-powershell.outputs.path }}"

  #  test2:
  #    needs: [test]
  #    runs-on: windows-latest
  #    steps:
  #      - name: test2 powershell
  #        shell: powershell
  #        run: |
  #          Write Output "${{ steps.test-powershell.outputs.path }}"
