name: hello world workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Python s端r端m端n端 belirtin

      - name: testing py
        run: |
          scriptPath = "./src/python/test.py"
  #        python $scriptPath
  #  goodbye:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: goodbye world
  #        run: echo ${{ github.workspace }}
  #        shell: bash

  #  test:
  #    needs: [hello, goodbye]
  #    runs-on: windows-latest
  #    steps:
  #      - name: test powershell
  #        id: test-powershell
  #        shell: powershell
  #        run: |
  #          Write-Output "path=Hello World 123"

  #  test2:
  #    needs: [test]
  #    runs-on: windows-latest
  #    steps:
  #      - name: test2 powershell
  #        shell: powershell
  #        run: |
  #          Write Output "${{ steps.test-powershell.outputs.path }}"
