name: hello world workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          ./src/hello.ps1

  #        python $scriptPath
  #  goodbye:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: goodbye world
  #        run: echo ${{ github.workspace }}
  #        shell: bash

  #  test:
  #    needs: [hello, goodbye]
  #    runs-on: windows-latest
  #    steps:
  #      - name: test powershell
  #        id: test-powershell
  #        shell: powershell
  #        run: |
  #          Write-Output "path=Hello World 123"

  #  test2:
  #    needs: [test]
  #    runs-on: windows-latest
  #    steps:
  #      - name: test2 powershell
  #        shell: powershell
  #        run: |
  #          Write Output "${{ steps.test-powershell.outputs.path }}"
