name: On Push Run

on: push

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.DEVOPS_DIR }}
          repository: "extendedkalman/test-repo"

      #- name: Set up Python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: 3.7

      - name: Run Python Script
        run: python ${{ env.DEVOPS_DIR }}/src/hello.py
        shell: sh

      - name: Execute Test Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: python ${{ env.DEVOPS_DIR }}/src/check.py