name: On Push Run

on: push

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/test-repo
          repository: "extendedkalman/test-repo"

      #- name: Set up Python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: 3.7

      - name: Run Python Script
        run: |
          $scriptPath=.\test-repo\src\hello.py
          python $scriptPath