name: On Push Run

on: push

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.DEVOPS_DIR }}
          repository: "extendedkalman/test-repo"

      #- name: Set up Python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: 3.7

      - name: Run Python Script
        run: python3 ${{ env.DEVOPS_DIR }}/src/hello.py
        shell: sh

      - name: Execute Test Script
        env:
          GITHUB_TOKEN: ${{ secrets.API}}
        run: python3 ${{ env.DEVOPS_DIR }}/src/check.py

  testrunnerkeyword:
    name: test runner
    runs-on: self-hosted
    steps:
      - name: test runner keyword
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(runner) }}'

  testing-webhook:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: write output
        run: |
          Write-Output ${{ secrets.GITHUB_TOKEN }}

      - name: "test"
        run: |
          $uri = "https://api.github.com/repos/extendedkalman/test-repo/dispatches"
          $headers = @{
              Authorization = "Bearer ${{ secrets.MYSECRET }}"
              Accept = "application/vnd.github.everest-preview+json" 
          }
          
          $body = @{
              event_type = "my-custom-event" 
          }
          
          $response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body ($body | ConvertTo-Json)
          Write-Output $response
          