name: usage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Özel Action'ı Kullan
      uses: ./.github/actions/action
      with:
        message: "Merhaba, Dünya!"
