name: Özel GitHub Action Kullanımı

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo'yu Çek
      uses: actions/checkout@v2

    - name: Özel Action'ı Kullan
      uses: ./.github/actions/hello-world-action
      with:
        message: "Merhaba, Dünya!"
