name: hello world workflow

on:
  repository_dispatch:
    types: [webhooktest]
  

jobs:
  run-my-script:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      
